### ISSUE TITLE
Variadic factorial function

### ISSUE THREAD

**Issue by jhowardjr** [variadicjs/variadic.js#50]
Request help creating a factorial function that calculates the factorial value of each parameter in the parameter list.

**Comment by devNoiseConsulting** [comment]
Trying to figure out edge cases. 18! is 6402373705728000 which is the last factorial we can calculate before the code will exceed the `Number.MIN_SAFE_INTEGER`. Do we limit all parameters to be 18 or less?

**Comment by D1esel-Dev** [comment]
i was thinking about this too.. maybe notation would be great for this just as a suggestion? like scientific??

**Comment by jhowardjr** [comment]
@redquark great observation!

**Comment by devNoiseConsulting** [comment]
Here's the code I have so far: https://github.com/devNoiseConsulting/variadic.js/blob/develop/lib/factorial.js

I'm doing the calculations, but also caching them so that we don't have to calculate every factorial and then using the highest value as the starting point for a new higher factorial.

In any case, I think we need to cap it at 18!. To overcome this we need to bring in a library that supports really big integers or we try to tackle that ourselves. Until either of those happen, I will write my error handling and test to work under that constraint.

**Comment by jhowardjr** [comment]
Nice memoization!

**Comment by devNoiseConsulting** [comment]
#59 closed this issue.
